[package]
name = "object-storage-ui"
description = "GPUI views/components：三栏 Workspace、Titlebar、Object Table、Command Palette"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
objc = "0.2"
raw-window-handle = "0.6"
object-storage-app = { workspace = true }
object-storage-core = { workspace = true }
object-storage-domain = { workspace = true }
object-storage-macos = { workspace = true }
object-storage-transfer = { workspace = true }
chrono = { workspace = true }
