[package]
name = "object-storage-app"
description = "Application Services：账号/任务编排等领域服务"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
object-storage-domain = { workspace = true }
object-storage-persistence = { workspace = true }
object-storage-macos = { workspace = true }
object-storage-core = { workspace = true }
object-storage-qiniu = { workspace = true }
object-storage-aliyun = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
