[package]
name = "object-storage-aliyun"
description = "Aliyun OSS Provider：实现 StorageProvider trait（OSS Signature V1）"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
object-storage-core = { workspace = true }
object-storage-domain = { workspace = true }
reqwest = { workspace = true }
hmac = { workspace = true }
sha1 = { workspace = true }
base64 = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
